<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<title>Max!</title>
		<link href="/css/smoothness/jquery-ui-1.9.1.custom.css" rel="stylesheet">
		<link rel="stylesheet" href="/css/layout.css">
		<style>body { background-color: #fefefe; } a img { border: none; }</style>
		<script src="/js/jquery.js"></script>
		<script src="/js/jquery-ui-1.9.1.custom.js"></script>
		<script src="/js/jquery.flot.js"></script>
		<script src="/js/jquery.flot.dashes.js"></script>
		<script src="/js/jquery.scrollTo-1.4.3.1.js"></script>
		<link rel="stylesheet" href="/css/bootstrap.css">
		<script src="/js/bootstrap-modal.js"></script>
		<script src="/js/bootstrap-twipsy.js"></script>
		<script src="/js/bootstrap-popover.js"></script>
		<script src="/js/spin.js"></script>
		<script src="/js/max.js"></script>
	</head>
	<body>
	 <?php echo $this->layout()->content; ?>
	</body>
</html>
